-- MySQL Script generated by MySQL Workbench
-- Tue Apr  8 19:53:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`actions_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actions_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`threads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`threads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_threads_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_threads_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commentscol` VARCHAR(45) NULL,
  `threads_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_threads1_idx` (`threads_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_threads1`
    FOREIGN KEY (`threads_id`)
    REFERENCES `mydb`.`threads` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`response_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`response_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `namer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME NOT NULL,
  `users_id` INT NULL,
  `threads_id` INT NULL,
  `comments_id` INT NULL,
  `actions_type_id` INT NOT NULL,
  `response_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_actions_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_actions_actions_type1_idx` (`actions_type_id` ASC) VISIBLE,
  INDEX `fk_actions_threads1_idx` (`threads_id` ASC) VISIBLE,
  INDEX `fk_actions_comments1_idx` (`comments_id` ASC) VISIBLE,
  INDEX `fk_actions_response_type1_idx` (`response_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_actions_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actions_actions_type1`
    FOREIGN KEY (`actions_type_id`)
    REFERENCES `mydb`.`actions_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actions_threads1`
    FOREIGN KEY (`threads_id`)
    REFERENCES `mydb`.`threads` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actions_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `mydb`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actions_response_type1`
    FOREIGN KEY (`response_type_id`)
    REFERENCES `mydb`.`response_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
